#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action ()
{
    case $1 in
        default) $OCAMLBUILD uuseg.cmx uuseg_string.cmx ;;
        tests)   $OCAMLBUILD test/tests.otarget ;;
        doc)     shift; pkg-doc $* doc/dev-api.docdir ;;
        api-doc) shift; pkg-doc $* doc/api.docdir ;;
        download-test-files) 
            test="Line Grapheme Word Sentence"
            for f in $test; do
                curl -# -S \
                "http://www.unicode.org/Public/UCD/latest/ucd/auxiliary/${f}BreakTest.txt" > test/${f}BreakTest.txt
            done
            ;;
        clean)   $OCAMLBUILD -clean ;;
        *)       $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
