#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

TEST_VERSION=${TEST_VERSION:=latest}

action ()
{
    case $1 in
        default) topkg build ;;
        doc)     shift; topkg doc --dev $* ;;
        api-doc) shift; topkg doc $* ;;
        test)    tokpg build && topkg test ;;
        download-test-files)
            test="Line Grapheme Word Sentence"
            for f in $test; do
                curl -# -S \
                "http://www.unicode.org/Public/$TEST_VERSION/ucd/auxiliary/${f}BreakTest.txt" > test/${f}BreakTest.txt
            done
            ;;
        clean)  topkg build clean ;;
        *)      $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
